export const ActionTypes = {
    SET_USERS: "SET_USERS",
    SET_PAGE_COUNT: "SET_PAGE_COUNT",
    SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
    SELECTED_USER: "SELECTED_USER",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
    CHANGE_EMAIL: "CHANGE_EMAIL",
};